@host = http://localhost/api

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "john@example.dev"
}

### Logout
POST {{host}}/logout

### Create user
POST {{host}}/users
Content-Type: application/json

{
    "email": "test@example.dev",
    "username": "test"
}

### Get users
GET {{host}}/users?username=doe

### Get user
GET {{host}}/users/john_doe

### Toggle follow
POST {{host}}/users/jane_doe/toggle_follow

### Create post
POST {{host}}/posts
Content-Type: application/json

{
    "content": "New post"
}

### Get posts
GET {{host}}/users/john_doe/posts

### Get post
GET {{host}}/posts/1

### Get feed
GET {{host}}/feed

### Create comment
POST {{host}}/posts/1/comments
Content-Type: application/json

{
    "content": "New comment"
}

### Get comments
GET {{host}}/posts/1/comments

### Toggle post like
POST {{host}}/posts/1/toggle_like

### Toggle comment like
POST {{host}}/comments/1/toggle_like
